/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Category: () => import('#controllers/category_controller'),
  Customer: () => import('#controllers/customer_controller'),
  Product: () => import('#controllers/product_controller'),
  Receipt: () => import('#controllers/receipt_controller'),
  Sale: () => import('#controllers/sale_controller'),
}
